"""empty message

Revision ID: 06ffedcdbff4
Revises: eab4a46cc4d8
Create Date: 2025-04-11 15:51:21.515870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ffedcdbff4'
down_revision = 'eab4a46cc4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
