"""empty message

Revision ID: 7fac44582cfb
Revises: 06ffedcdbff4
Create Date: 2025-04-11 16:00:59.490007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fac44582cfb'
down_revision = '06ffedcdbff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
