"""empty message

Revision ID: c5e120a1bb7a
Revises: 7fac44582cfb
Create Date: 2025-04-11 16:10:10.275973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e120a1bb7a'
down_revision = '7fac44582cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_models', schema=None) as batch_op:
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###
