"""Describe your changes here.

Revision ID: dacfd7955ff9
Revises: add_chat_tables
Create Date: 2025-04-10 14:56:17.480391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dacfd7955ff9'
down_revision = 'add_chat_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('withdraw_configs')
    op.drop_table('project')
    with op.batch_alter_table('daily_profits', schema=None) as batch_op:
        batch_op.drop_constraint('daily_profits_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('daily_profits_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('daily_profits_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'investments', ['investment_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_constraint('investments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('investments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('recharges', schema=None) as batch_op:
        batch_op.drop_constraint('recharges_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_constraint('referral_bonuses_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('referral_bonuses_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('referral_bonuses_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'investments', ['investment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('users_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'])

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint('withdrawals_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('withdrawals_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['processed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('withdrawals_ibfk_2', 'users', ['processed_by'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('withdrawals_ibfk_1', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_2', 'users', ['referrer_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('users_ibfk_1', 'roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('referral_bonuses_ibfk_2', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('referral_bonuses_ibfk_1', 'users', ['referrer_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('referral_bonuses_ibfk_3', 'investments', ['investment_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('recharges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recharges_ibfk_1', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('investments_ibfk_1', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('investments_ibfk_2', 'projects', ['project_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('daily_profits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('daily_profits_ibfk_1', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('daily_profits_ibfk_2', 'projects', ['project_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('daily_profits_ibfk_3', 'investments', ['investment_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    op.create_table('project',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('target_amount', mysql.FLOAT(), nullable=False),
    sa.Column('current_amount', mysql.FLOAT(), nullable=True),
    sa.Column('share_price', mysql.FLOAT(), nullable=False),
    sa.Column('total_shares', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_shares', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_roi', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('withdraw_configs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('min_amount', mysql.FLOAT(), nullable=False),
    sa.Column('max_amount', mysql.FLOAT(), nullable=False),
    sa.Column('fee_rate', mysql.FLOAT(), nullable=False),
    sa.Column('daily_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
