"""empty message

Revision ID: eab4a46cc4d8
Revises: dacfd7955ff9
Create Date: 2025-04-11 15:37:01.713396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab4a46cc4d8'
down_revision = 'dacfd7955ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_models')
    # ### end Alembic commands ###
